### PR TITLE
Fixed `Dark Mode` issue

### PR DESCRIPTION
**Pull request by Somesh-Mallewar**
Hello Project Admin,

Issue Number : #326 

## Video:

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/118499404/53c8c14e-749b-415e-a119-41b93fb712af

### CODE REVIEW

**Comment by Somesh-Mallewar** [comment]
@AshutoshDash1999 ,
Please review this.

**Comment by AshutoshDash1999** [comment]
@Somesh-Mallewar please dont submit PR if you are not assigned with the issue

**Comment by Somesh-Mallewar** [comment]
> @Somesh-Mallewar please dont submit PR if you are not assigned with the issue

But it's a major issue. I think this PR will help the codebase.

**Comment by Somesh-Mallewar** [comment]
@AshutoshDash1999 ,
Please review it once.

**Comment by AshutoshDash1999** [comment]
> > @Somesh-Mallewar please dont submit PR if you are not assigned with the issue
> 
> But it's a major issue. I think this PR will help the codebase.

That doesn't mean you won't follow GSSOC rules.

**Comment by AshutoshDash1999** [comment]
Please keep the default theme as dark.

**Pull request closed without merging**
