### PR TITLE
toggle-button-changed

### PR DESCRIPTION
**Pull request by khadar1020**
issue: #460 
I have changed the toggle button between dark and light themes I have tried so many colors and only these colors were looking nice so I have used them I think these are better than before

Screenshot (689)

Screenshot (690)

### CODE REVIEW

**Comment by khadar1020** [comment]
can you please review my pr @AshutoshDash1999

**Comment by khadar1020** [comment]
can you please review my pr @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
please fix the spacing
image
 also choose a better icon for the half moon or sun.

**Comment by khadar1020** [comment]
Ok @AshutoshDash1999 I will do it

**Comment by AshutoshDash1999** [comment]
hi @khadar1020, would you like to complete this pending PR?

**Comment by khadar1020** [comment]
I am writing semester-end exams now I will do it in a week and send PR sorry for the delay @AshutoshDash1999 .

**Pull request closed without merging**
