### PR TITLE
Added Favicon Path

### PR DESCRIPTION
**Pull request by Parul1606**
Closes issue #309 
I have added the favicon image at the correct path.
File should be placed in the main website folder only.

An image has been attached and we have other 2 options for the logo . I'm attaching the other 2 images too here. If you want to change the logo please let me know.
1.
image

2.
image

Results: -
After making changes this is the result I've got.
image

### CODE REVIEW

**Comment by Parul1606** [comment]
I have checked its working in both smartphone and laptop.

**Comment by AshutoshDash1999** [comment]
@Parul1606 the icon doesn't appear on deploy preview link

**Comment by Parul1606** [comment]
@AshutoshDash1999 Its working.
image

**Comment by Parul1606** [comment]
Please also assign me also otherwise my score won't count @AshutoshDash1999

**Pull request merged**
