### PR TITLE
Added Scroll-to-Top button

### PR DESCRIPTION
**Pull request by harshitakaushik-dev**
With additional functionality of progress tracker.
preview1

Thank you for allowing me this contribution under GSSoC '23.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@harshita-kaushik2 can you please submit a video/gif of what you have done? also does the button changes in response to dark/light mode?

**Comment by harshitakaushik-dev** [comment]
Yeah sure, here is the video. 
- The button is perfectly functional in both light and dark mode
- Displays progress of the webpage as 0 at the landing page and 100 at the end of it.
- Smooth flow of the page to the top on the button being clicked.


https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112249538/2cee518b-a45a-4652-ba32-0fc993d43477

**Comment by AshutoshDash1999** [comment]
thats cool...i guess the icon of arrow can be improve...may add this
image

also please move the javascript part to different file

**Comment by harshitakaushik-dev** [comment]
### Here is a video to illustrate the changes :


https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112249538/7d094849-0c37-48a7-a7b0-a79df31f1f5e

The JS file has been added to a different folder as well.

**Comment by AshutoshDash1999** [comment]
btw is it responsive too? have you checked on that part??

**Comment by harshitakaushik-dev** [comment]
@AshutoshDash1999 Yes, it is responsive in both light and dark mode. Checked that as well !!

**Comment by harshitakaushik-dev** [comment]
Here is a video to demonstrate the same :

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/112249538/353923ef-2c2b-4b52-a166-3ca089b7c138

**Comment by AshutoshDash1999** [comment]
Ok, that's great.

Thank you @harshita-kaushik2 for contributing to this repo and making it better. People like you make us believe in open source.

**Comment by AshutoshDash1999** [comment]
Issue id: #35

**Review by ramanujamgond — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
