### PR TITLE
[#199]Enhanced No Icons found section

### PR DESCRIPTION
**Pull request by NehaKariya0309**
Issue #199 

Changes made in the No Icons found section :
1. Added an emoji to make the interface engaging.
2. Modified the no icons found message with a clearer message.

Before changes:
Screenshot (97)

After changes:
Screenshot (99)

Kindly review the changes made.
Regards,
Neha Kariya

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@NehaKariya0309 can you please mention issue number here?

**Comment by NehaKariya0309** [comment]
@AshutoshDash1999 , issue number #199 .

**Comment by AshutoshDash1999** [comment]
@NehaKariya0309 please improve the error message. P.S. We are not using any filters. Please minify the icon... 119 Kb is too much

**Comment by NehaKariya0309** [comment]
@AshutoshDash1999 ,the suggested changes have been made.
Kindly review them.
Screenshot (100)

**Comment by AshutoshDash1999** [comment]
@NehaKariya0309 please minify the file size of icon... i was not mentioning about the height. Please add the CSS only in CSS file not in HTML file.
image

**Comment by NehaKariya0309** [comment]
@AshutoshDash1999 , sorry for the misunderstanding. 
Compressed the image to 49 KB and moved inline style to style.css (both light and dark mode).

**Pull request merged**
