### PR TITLE
Issue#169  Made the header attarctive

### PR DESCRIPTION
**Pull request by abansal15**
Screenshot_2023-07-21-12-47-43-880_com android chrome
Made the header responsive and attractive in mobile view.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
Please describe what you have done with screenshots. Title is not meaningfull

**Comment by abansal15** [comment]
> Please describe what you have done with screenshots. Title is not meaningfull

Done

**Comment by AshutoshDash1999** [comment]
please resolve merge conflicts

**Comment by abansal15** [comment]
ok

**Comment by abansal15** [comment]
@AshutoshDash1999 resolved the merge conflit

**Comment by AshutoshDash1999** [comment]
please fix this
image

**Comment by abansal15** [comment]
@AshutoshDash1999 done
image

**Comment by abansal15** [comment]
@AshutoshDash1999 please review it

**Comment by AshutoshDash1999** [comment]
it's same
image

Please take a pull from the dev branch

**Comment by abansal15** [comment]
@AshutoshDash1999 is it ok? now there is gap between the download and star repo button
image

**Comment by AshutoshDash1999** [comment]
@abansal15  better, but please resolve the merge conflicts

**Comment by abansal15** [comment]
@AshutoshDash1999 done please review it

**Comment by abansal15** [comment]
@AshutoshDash1999 please review it

**Comment by AshutoshDash1999** [comment]
@abansal15 please check the page after solving merge conflicts
image

Also you haven't resolved the review yet

**Comment by abansal15** [comment]
@AshutoshDash1999 please ignore this pr i dont get to know why on rasing pr and then seeing the preview i has error but on my local everything is fine

**Comment by abansal15** [comment]
@AshutoshDash1999  please see this pr i have done all the changes
image
image

**Comment by abansal15** [comment]
@AshutoshDash1999 can you please see it and review it asap so that no other one do changes to this page and no meregr conflit can come

**Comment by AshutoshDash1999** [comment]
#169

**Pull request merged**
