### PR TITLE
modify the navbar

### PR DESCRIPTION
**Pull request by parasss19**
## Description 
- Modify the navbar
- Added proper glassmorphism effect with proper blur and border effect
- Made the navbar sticky (with very minimum code)

## Screenshot

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/101205226/7a50448b-9ce4-46aa-95ec-877fe83241b3

### CODE REVIEW

**Comment by parasss19** [comment]
Hey @AshutoshDash1999 Please review it

**Comment by AshutoshDash1999** [comment]
- remove the border
- decrease the padding in y-axis
- increase the blur

why have you added styling inline when there is separate file for CSS?

**Comment by parasss19** [comment]
> * remove the border
> * decrease the padding in y-axis
> * increase the blur
> 
> why have you added styling inline when there is separate file for CSS?

Actually the css is not working when i write in  separate css file

**Comment by AshutoshDash1999** [comment]
> Actually the css is not working when i write in separate css file

that means another CSS is overriding it. Please debug that

**Comment by parasss19** [comment]
> > Actually the css is not working when i write in separate css file
> 
> that means another CSS is overriding it. Please debug that

actually your are using cdn files thats why its happening and i dont know much about that so cant help in debug

**Comment by AshutoshDash1999** [comment]
I can't accept the PR unless its good enough to be accepted.

**Comment by parasss19** [comment]
> I can't accept the PR unless its good enough to be accepted.

I am busy assigned someone else

**Pull request closed without merging**
