### PR TITLE
Create npm package for react

### PR DESCRIPTION
**Pull request by kartikjoshi267**
# Description
This PR is created to create an NPM package for the React based icon components for the Bookingjini-icons. It introduces the following changes:
1. Adds the files related to the npm package into the package folder.
2. Updates the website design to accomodate the React icons feature.
3. Updates the documentation for react icons.

Related to the issue #219 

## Additional Context
I request the owner to review the changes and suggest any changes. If no changes are required, then please publish the package on npm.

_Regards_
_Kartik Joshi_

### CODE REVIEW

**Comment by kartikjoshi267** [comment]
@AshutoshDash1999 please review this PR

**Comment by AshutoshDash1999** [comment]
please resolve merge conflicts

**Comment by kartikjoshi267** [comment]
> please resolve merge conflicts

@AshutoshDash1999  Please check now!

**Comment by AshutoshDash1999** [comment]
@kartikjoshi267 how can we test this in local?

**Comment by kartikjoshi267** [comment]
> @kartikjoshi267 how can we test this in local?

Firstly build the package by running
```shell
npm install && npm run build
```

You can load the package into an existing React or NextJS project by using 
```shell
npm pack <path of the package folder>
```

A .tgz file will be created in your project folder.

Then, install it
```shell
npm install <name of .tgz file automatically created>
```

Then 
```javascript
import { JiniAc } from 'bookingjini-react-icons';
```

**Comment by kartikjoshi267** [comment]
@AshutoshDash1999 please review this PR!!

**Comment by AshutoshDash1999** [comment]
@kartikjoshi267 can you help me with this?
image

**Comment by kartikjoshi267** [comment]
Please modify the command with name of the .tgz file with extension

**Comment by AshutoshDash1999** [comment]
@kartikjoshi267 please remove `Jini` from icon name
image

**Comment by kartikjoshi267** [comment]
> @kartikjoshi267 please remove `Jini` from icon name
> image
> 

Shall I open another issue and a new PR?

**Comment by AshutoshDash1999** [comment]
Ok but take the latest pull from the dev branch.
1. Create a issue
2. Work on the issue only after you are assinged

**Comment by kartikjoshi267** [comment]
> Ok but take the latest pull from the dev branch.
> 
> 1. Create a issue
> 2. Work on the issue only after you are assinged

Please assign me #350 so that I can start working on it.

**Comment by AshutoshDash1999** [comment]
@kartikjoshi267 also can you fix this?

image

**Comment by kartikjoshi267** [comment]
> @kartikjoshi267 also can you fix this?
> 
> image
> 

The image?

**Comment by AshutoshDash1999** [comment]
> > @kartikjoshi267 also can you fix this?
> > image
> 
> The image?

yes

**Comment by kartikjoshi267** [comment]
Please assign issue #400 to me so that I can fix the issue!

**Pull request merged**
