### PR TITLE
#85

### PR DESCRIPTION
**Pull request by PrathamAsrani**
Dear Team,
The about us and contact us page is ready for the respective website just we need to add the respective data like(email, address, and phone number. I would Update the fonts for the site soon.
Requesting to provide the contact section details for the respective users.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
- Why have you made the top bar fixed? 
- Why there is a big gap between search bar and icons?
- Where are you adding the contact info?

**Comment by PrathamAsrani** [comment]
> * Why have you made the top bar fixed?
> * Why there is a big gap between search bar and icons?
> * Where are you adding the contact info?

1. Navbar: That looks good that's why but sir if you don't like it I will make that same as before.
2. I will check for that gap sir.
3. For any inconveniences if someone wants to connact, because in many websites it's good to show the team contact details. Other wise many people think low quality firm. 

Conclusion: I will make the Navbar like previous and remove that gap, please confirm me for the contact details if you say I will remove that too.

**Comment by AshutoshDash1999** [comment]
1. Please make it the same as before
3. Over time we evolved to know what our needs are. We have added LinkedIn, facebook and insta id so that people can connect with us.

**Comment by PrathamAsrani** [comment]
> 1. Please make it the same as before
> 2. Over time we evolved to know what our needs are. We have added LinkedIn, facebook and insta id so that people can connect with us.

Ohk sir, I will make it as before. With just About Us section

**Pull request closed without merging**
