### PR TITLE
Added design png

### PR DESCRIPTION
**Pull request by Ks103**
The designs I added the png in assest folder, please verify also sharing you the figma url and fonts I used are:
1) Heading: Finger Paint
2) sub-head: Fenix
3) Others: Poppins.

Hope you like the changes I made. Requesting you to please verify and merge my pr. 

figma link: https://www.figma.com/file/U5602mok76eMjrAMlSbXNq/Bookingjini-icons?type=design&node-id=1%3A147&t=OySa1bN49Ebs3M2g-1
Screenshot 2023-05-25 134548

### CODE REVIEW

**Comment by Ks103** [comment]
Changed css hover effects color. Please verify and merge my pr

Screenshot 2023-05-25 203639

**Comment by AshutoshDash1999** [comment]
@Ks103 please make the shadow very subtle, yours is too deep. Also, I guess you can improve on the design part too. The current ones are not at all appealing.

**Comment by Ks103** [comment]
Ok will do

**Comment by Ks103** [comment]
I have changed the styling as well as the design please check request you to check and merge my pr. @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@Ks103 please share updated screenshot

**Comment by Ks103** [comment]
design ss

Desktop - 3
Desktop - 1

updated css ss

Screenshot (131)
Screenshot (132)

**Comment by Ks103** [comment]
please verify @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
@Ks103 please don't add any fonts for now. The fonts you are suggesting don't go well with the website. Please refer to https://tablericons.com/. You can see each icon box has a very subtle shadow. Please add that in both light/dark modes.

**Pull request closed without merging**
