### PR TITLE
feat: add commit history link with minor styling

### LINKED ISSUE #428: feat: add a link to show author commit history
### Is your feature request related to a problem? Please describe.

image

> Author commit history of `AshutoshDash1999`
https://github.com/Bookingjini-Labs/bookingjini-icons/commits?author=AshutoshDash1999

### Describe the solution you'd like

- We can replace the long text of `View Profile` to `GitHub`
- We can add another button but it will make it very tough to read due to less space. (I can try)
- Or we can simple display two icons
- Or we can just add a link to `Contributions: <number>` with the appropriate link above the current CTA

Let me know what you think, and if you need some clarification.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Related Issue

Resolves #428 

## Description

- It is dynamic URL using `contributor.login` fetched data

## Screenshots

image

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
The underlining doesn't look good. Can hide the underline and only show when someone hovers on it?

**Comment by Anmol-Baranwal** [comment]
> The underlining doesn't look good. Can hide the underline and only show when someone hovers on it?

Done.

**Comment by AshutoshDash1999** [comment]
Can you add a little bit of spacing?

image

**Comment by Anmol-Baranwal** [comment]
> Can you add a little bit of spacing?
> 
> image

CSS doesn't allow this. Can you mention any specific approach that I should use?

> Also, I strongly believe this is good. Doing extra styling is overkill most of the times.

I have tried, I can't implement this. Please help me with code or suggest something.

**Comment by AshutoshDash1999** [comment]
> CSS doesn't allow this. Can you mention any specific approach that I should use?

add padding and instead of `text-underline` use `border-bottom`.

> > Also, I strongly believe this is good. Doing extra styling is overkill most of the times.

just add 1-2px of padding and it will be good to go. The underline is too much attached to the text.

**Comment by Anmol-Baranwal** [comment]
I have made the changes. Let me know if you need further changes.

**Comment by AshutoshDash1999** [comment]
looks better

**Pull request merged**
