### PR TITLE
Meta tags added

### PR DESCRIPTION
**Pull request by M-A-N-I-K**
This pull request adds a description about meta tags to the documentation. Meta tags are small snippets of text that provide information about a web page to search engines and other web services. They are typically included in the head section of an HTML document.

Changes

-     A new section has been added to the documentation titled "Primary Meta Tags."

Issue #198

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@M-A-N-I-K can you please tag the issue number here?

**Comment by AshutoshDash1999** [comment]
@M-A-N-I-K please fix the merge conflicts

**Comment by M-A-N-I-K** [comment]
@AshutoshDash1999  Merge conflicts resolved!

**Comment by AshutoshDash1999** [comment]
can you take a pull and then push the code? Your branch doesn't show the favicon in preview deploy

**Comment by M-A-N-I-K** [comment]
@AshutoshDash1999  now check

**Comment by AshutoshDash1999** [comment]
the favicon is still not visible in the deploy preview.

**Pull request closed without merging**
