### PR TITLE
Footer added for light and dark mode

### PR DESCRIPTION
**Pull request by Sakar95**
This PR addresses issue #104
I have added the footer section containing the copyright  text  which is visible in both lighter and darker mode

After_1
After_2

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@Sakar95 please remove merge conflicts. Please take a pull from dev branch before adding your code.

**Comment by Sakar95** [comment]
@AshutoshDash1999 I have resolved all the conflicts. Please have a look

**Comment by AshutoshDash1999** [comment]
@Sakar95 please resolve merge conflicts.

**Comment by Sakar95** [comment]
Done sir @AshutoshDash1999

**Pull request merged**
