### PR TITLE
Enhance CDN Accessibility for Improved User Experience

### PR DESCRIPTION
**Pull request by premsaivarmachekuri**
Issue #110 

## Solution

To address these challenges and enhance the accessibility of the CDN, the following improvements have been implemented:

- **Prominent Display of CDN Information:** The CDN information is now prominently placed above the search icon on the website. This ensures its visibility and easy access for users, eliminating the need for extra navigation.

- **Clear Instructions:** Clear instructions have been provided on how users can utilize the CDN to access icons and code snippets. Step-by-step guidance is included to help users copy the CDN links and incorporate them into their code effortlessly.

- **Simplified Icon Access Process:** A dedicated section or page has been created to list available icons along with their corresponding CDN links. Users can easily browse through the options and directly copy the necessary CDN links, streamlining the icon access process.

- **Responsive Design:** The website and the section displaying CDN information and icons have been optimized for responsive design, ensuring a seamless user experience across different screen sizes and devices.

## Screenshots
Mobile:
image
Tablet:
image
Desktop: 
image

- By merging this PR, users will benefit from enhanced accessibility to the CDN, ensuring easy access to icons and significantly improving the ease of use. 
- The prominent display of CDN information, along with clear instructions, simplifies the process of copying CDN links for icons. 
- This update enhances the overall usability and user experience, making it effortless to leverage the CDN and its resources.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@premsaivarmachekuri what is ```Simplified Icon Access Process``` about?

**Comment by premsaivarmachekuri** [comment]
I mean by providing the steps of pasting the CDN in HTML and then copying
the icon code they want and paste it into there code. This is the process I
mean.

**Comment by AshutoshDash1999** [comment]
@premsaivarmachekuri please fix the issue in light mode too

image

**Comment by premsaivarmachekuri** [comment]
Sure, will do that.

**Pull request merged**
