### PR TITLE
Issue #103 resolved : Improved the UI : Added borders and improved hover on the icon cards for both light and dark mode

### PR DESCRIPTION
**Pull request by Hardikaz**
# Issue #103 Improvement in the UI solved
<ol>
<li>Added Borders to the icon cards</li>
<li>Improved Hover properties</li>
<li>For both light and dark mode</li>
<li>Added transition property</li>
</ol>

# 1
- Added borders : for light mode , improved hover property and added transition
  
image

# 2
- Added borders : for dark mode , improved hover property and added transition
  
image

- Anticipating your response

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
please don't add border...the hover ease out effect is not smooth... the hover color is not good...make it little dark grey for dark mode...and subtle gray for white... please maintain the old website ui

**Comment by Hardikaz** [comment]
ok sir I will do that

**Comment by Hardikaz** [comment]
# I have made the changes required Please have a look

1
image

- This is for the the light mode

2
image

- This is for the dark mode

- Please have a look at it sir

**Comment by AshutoshDash1999** [comment]
@Hardikaz the changes you have done are already present on the website. You have just changed the colour and transition timing, which is not adding anything. If possible make the hover-out property smoother.

**Pull request closed without merging**
