### PR TITLE
#445 navbar update

### PR DESCRIPTION
**Pull request by PVBharadwaj**
@AshutoshDash1999  please review this pr under gssoc'23

### CODE REVIEW

**Comment by PVBharadwaj** [comment]
Closes #445

**Comment by PVBharadwaj** [comment]
image

in light mode


image

in dark mode

**Comment by AshutoshDash1999** [comment]
the switch button is a little below
image

**Comment by PVBharadwaj** [comment]
@AshutoshDash1999 I have updated the pr. Please review it under gssoc'23

**Comment by AshutoshDash1999** [comment]
the issue is still there

image

**Pull request closed without merging**
