### PR TITLE
toggle button enhancement successfully done

### PR DESCRIPTION
**Pull request by HimanshuNarware**
#Description
toggle-button enhancement successfully done. The new design of the toggle button is the most UI-comfortable design. This will improve the UI of the website.

##issue code.
#304
##changes
-Added a more attractive design of the toggle button
-Added new CSS properties to toggle
-Fix the previous bugs

Screenshot/video

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/83147410/d26436e7-85bb-441a-92b1-566c668dc228

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
- For the toggler please keep the switch UI
- Both the SVG is overlapping 
image

- The toggle bug is not fixed yet.

**Comment by HimanshuNarware** [comment]
@AshutoshDash1999 
both the SVG is overlapping bus is fixed
#Video

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/83147410/35099790-69ff-4173-9a37-0b90e6fb62d1

**Comment by AshutoshDash1999** [comment]
The toggler bug has not been fixed yet.

**Comment by HimanshuNarware** [comment]
> * For the toggler please keep the switch UI

@AshutoshDash1999 For the toggler use the switch UI i think this is the problem

**Comment by AshutoshDash1999** [comment]
> @AshutoshDash1999 For the toggler use the switch UI i think this is the problem

i guess that was assigned to you...right?

**Comment by HimanshuNarware** [comment]
> > @AshutoshDash1999 For the toggler use the switch UI i think this is the problem
> 
> i guess that was assigned to you...right?

yeah 

> The toggler bug has not been fixed yet.

which bug

**Comment by AshutoshDash1999** [comment]
The initial switching doesn't exactly correlate with the theme.

**Comment by HimanshuNarware** [comment]
> The initial switching doesn't exactly correlate with the theme.

ohh now i get the issue

**Comment by AshutoshDash1999** [comment]
are you working on this?

**Comment by HimanshuNarware** [comment]
> are you working on this?


@AshutoshDash1999  I tried to solve this issue but I don't find anything useful to solve this. can you please help me to solve this issue?

**Pull request closed without merging**
