### PR TITLE
Fixed the light mode and made enhancements in dark mode

### PR DESCRIPTION
**Pull request by Tanishashrivas**
The light mode now looks so pretty according to me. Created hover effects for both the modes and fixed some color glitches of the links as well. 
GSSOC23 contributor

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
can you mention the assigned issue number?

Issue: #390

**Comment by AshutoshDash1999** [comment]
> The light mode now looks so pretty according to me. 

Don't want to offend, but this is worse.

image

**Comment by Tanishashrivas** [comment]
> can you mention the assigned issue number?

I wasn't assigned one, i thought you can work on issues 😞 sorry I'm new to this contribution stuff and I'm trying

**Comment by Tanishashrivas** [comment]
> 
The white one looked straining to the eyes :) I'm sorry if I cannot meet your expectations but I was looking forward for atleast one successful contribution

**Comment by AshutoshDash1999** [comment]
> I wasn't assigned one, i thought you can work on issues 😞 sorry I'm new to this contribution stuff and I'm trying

No Tanisha, this is not how open source works. First, you'll need to create an issue, wait for that issue to be assigned and then work on that.

> The white one looked straining to the eyes 

That's why dark mode exists. 

> I was looking forward for atleast one successful contribution

That doesn't mean you will submit spammy PR.

**Comment by Tanishashrivas** [comment]
> > I wasn't assigned one, i thought you can work on issues 😞 sorry I'm new to this contribution stuff and I'm trying
> 
> No Tanisha, this is not how open source works. First, you'll need to create an issue, wait for that issue to be assigned and then work on that.
> 
> > The white one looked straining to the eyes
> 
> That's why dark mode exists.
> 
> > I was looking forward for atleast one successful contribution
> 
> That doesn't mean you will submit spammy PR.

I get it, i will keep it in mind from now on :)

**Pull request closed without merging**
