### PR TITLE
<Dark mode Enhancement> #475 Resolved

### LINKED ISSUE #475: [FEATURE] <Dark mode Enhancement>
### Description

The default setting of the website is set to dark mode, but when a user switch to light mode and reloads the webpage or clicks on any button the light mode instantly gets disabled which does not look appealing as a visitor.
I am willing to work on this bug and want to enhance the UX experience using JavaScript.
Please assign this to me under GSSOC23.

### Describe the solution you'd like

When a user switch to light mode the theme must remain the same until the user is there but it does not happen in this case, so I want to improve this feature of switching between dark mode. 

### Describe alternatives you've considered

I want to work on this storage feature with the help of JavaScript that theme remains the same until the user's session expires.

### Additional context

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)
- [X] I will work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Manishak798**
I have entirely written the JS code for the theme toggler and also provide a local storage functionality that will save user data locally. Kindly check my PR and let me know your views on the same @AshutoshDash1999 
image

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@Manishak798 please fix this.
 
also give proper title to your PR

image

**Comment by Manishak798** [comment]
image
Hey, @AshutoshDash1999 I have made the changes accordingly and also changed the name of my PR please check the PR now and let me know your views.

**Comment by Manishak798** [comment]
Hey @AshutoshDash1999 Kindly check my PR.

**Comment by AshutoshDash1999** [comment]
Next time please add the issue number in the description

#475

**Pull request merged**
