### PR TITLE
added a typing effect to subtitle

### LINKED ISSUE #97: we can animate the Text ?
instead of this plain text we  can have animation of text like typing effect. please assign me this issue. i am happy to work with you 

Screenshot 2023-05-24 011222

### PR DESCRIPTION
**Pull request by codewithnadeem14502**
Fix #97 issue 
please have a look on demo video below hope you like my work 

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/105824474/1888f639-61b1-4fac-96c9-08a4b78159ef

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@codewithnadeem14502 that's good but can you mention which issue you have linked to?

**Comment by codewithnadeem14502** [comment]
Done check once

**Comment by bookingjini** [comment]
> codewithnadeem14502

@codewithnadeem14502 - Kindly fix the conflict.

**Comment by AshutoshDash1999** [comment]
@codewithnadeem14502 although I appreciate your effort, I want you to be more creative with this typing effect. We don't need it if you just want to show a typing effect for a single whole line...

**Comment by codewithnadeem14502** [comment]
pls check now ?
let me know the status

**Comment by AshutoshDash1999** [comment]
@codewithnadeem14502 can you please resolve merge conflict

**Comment by codewithnadeem14502** [comment]
hey bro, i am new to open source i don 't know about this, why and how to resolved the conflict?
please share your info so that it can be helpful for other also

**Comment by AshutoshDash1999** [comment]
@codewithnadeem14502 The way to learn is through experiments and exploration. Please learn about resolving merge conflicts from youtube or try learning it from blogs.

**Pull request closed without merging**
