### PR TITLE
Fix issue reponsive #95

### PR DESCRIPTION
**Pull request by crocmons**
**searchbar and hero section text is now responsive for all devices also I make the whole website responsive #95**

bookingjini project gssoc23
bookingjini project gssoc23 img 2

### CODE REVIEW

**Review by ramanujamgond — APPROVED** [review]
Thank you for your contribution.

**Comment by ramanujamgond** [comment]
> **searchbar and hero section text is now responsive for all devices also I make the whole website responsive #95**
> 
> bookingjini project gssoc23 bookingjini project gssoc23 img 2

@crocmons - Kindly resolve the conflicts

**Review by ramanujamgond — COMMENTED** [review]
Kindly fix the conflicts

**Comment by crocmons** [comment]
> Kindly fix the conflicts

resolve the conflicts

**Pull request merged**
