### PR TITLE
added a typing effect on landing page

### PR DESCRIPTION
**Pull request by Arjundotadex**
image
Used Javascript to add a text typing effect on the landing page.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@Arjundotadex can you mention the assigned issue number?

**Comment by Arjundotadex** [comment]
@AshutoshDash1999 I have added the issue number pls cross check

**Comment by AshutoshDash1999** [comment]
> @AshutoshDash1999 I have added the issue number pls cross check

Add it to the description. Also, you have added the pull request number and not issue number.

**Comment by Arjundotadex** [comment]
image
Used Javascript to add a text typing effect on the landing page. 
PR #398

**Comment by AshutoshDash1999** [comment]
@Arjundotadex is this PR associated with any issue ??

**Comment by Arjundotadex** [comment]
No @AshutoshDash1999
This PR is not associated with any issue.

**Comment by AshutoshDash1999** [comment]
you are participating under GSSOC right?

**Pull request closed without merging**
