### PR TITLE
Added Favicon Path

### PR DESCRIPTION
**Pull request by Parul1606**
Closes Issue #309 
I have added the favicon image at the correct path. 
File should be placed in the main website folder only.

An image has been attached and we have other 2 options for the logo . I'm attaching the other 2 images too here. If you want to change the logo please let me know.
1. 
favicon

2.
logo

Results: -
After making changes this is the result I've got.
image

### CODE REVIEW

**Comment by Parul1606** [comment]
I have checked its working on both mobile and deploy preview🙌🏼. Please let me know if you require any changes.

**Comment by Parul1606** [comment]
Please review.

**Comment by AshutoshDash1999** [comment]
@Parul1606 
1. Why your PR title is `Testing`?
2. Please resolve merge conflicts.

**Comment by Parul1606** [comment]
Please check if it is ok now?

**Comment by AshutoshDash1999** [comment]
@Parul1606 Please take a pull from the `dev` branch and then add your code and push it.

**Comment by Parul1606** [comment]
I'm making a new PR unnecessary files are added while committing.

**Comment by Parul1606** [comment]
So sorry for the inconvenience caused.

**Pull request closed without merging**
