### PR TITLE
Added No Result Found

### PR DESCRIPTION
**Pull request by TusharUtane07**
Added the feature No Result Found when there is no font found in the Data.

### CODE REVIEW

**Comment by TusharUtane07** [comment]
@AshutoshDash1999 Please check the PR I made a Important change and closed issue #15

**Review by ramanujamgond — APPROVED** [review]
Thank you for your contribution

**Comment by ramanujamgond** [comment]
@TusharUtane07 - Kindly resolve the conflict.

**Comment by AshutoshDash1999** [comment]
@TusharUtane07 since you didn't give any update on this PR, I am closing this issue.

**Pull request closed without merging**
