### PR TITLE
#419 Added sign in Page..... 

### PR DESCRIPTION
**Pull request by ankit071105**

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
was this issue assigned to you? Have you discussed on this from anyone from the Bookingjini?

**Comment by ankit071105** [comment]
But i have the solution for that issue so I resolve that issue

**Comment by AshutoshDash1999** [comment]
no @ankit071105 this is not how it's done. You have to follow the GSSOC rules

**Comment by ankit071105** [comment]
okay bro sorry @AshutoshDash1999  for that now I can resolve that issue... I have created a Sign In for solving that issue atleast I can be a part of that

**Pull request closed without merging**
