### PR TITLE
Changed the header buttons. Added Gradient on buttons. made them more highlighted.

### PR DESCRIPTION
**Pull request by 1Shubham7**
Changed the appearance of the header buttons by adding gradient and some more css.
Now they look like this : 
issue1

### CODE REVIEW

**Comment by 1Shubham7** [comment]
I am participating in GSSoC. But I can't get how to add GSSoC label to this pull request. Can someone please help me around it.

**Comment by 1Shubham7** [comment]
Somebody please review it, I want to merge more commits.

**Comment by ramanujamgond** [comment]
@1Shubham7 - Kindly resolve the conflict.

**Comment by 1Shubham7** [comment]
@ramanujamgond , Thank you for your suggestion. I will surely resolve the conflicts.

**Comment by AshutoshDash1999** [comment]
@1Shubham7 please make some improvements on the button part. The gradient button is not looking good. Please refer some examples.

**Comment by 1Shubham7** [comment]
oh really @AshutoshDash1999, I thought it was looking good. Ok, I will surely make it better.

**Comment by bookingjini** [comment]
> oh really @AshutoshDash1999, I thought it was looking good. Ok, I will surely make it better.

@1Shubham7 - Kindly go with the theme color, Maintain color balance and symmetry. Just have a little look at the color theory to get some idea.

**Comment by 1Shubham7** [comment]
@bookingjini I got your point, I will bring up something better next time.

**Comment by AshutoshDash1999** [comment]
@1Shubham7 Please resolve the merge conflicts

**Comment by 1Shubham7** [comment]
@AshutoshDash1999 
I have designed some more buttons. Please have a look and tell me if anyone is good enough or should I try designing more. 
buttons_options

Please do you reply me soon.

**Comment by AshutoshDash1999** [comment]
Instead of a button, can you create a switch? Its more closer to what we are looking for.

**Comment by 1Shubham7** [comment]
@AshutoshDash1999 ok git it. I will soon show you some switch designs.

**Review by 1Shubham7 — COMMENTED** [review]
OK.

**Pull request closed without merging**
