### PR TITLE
Fixed #15

### LINKED ISSUE #15: Showing "No Result Found"
When performing a search, if no icon is found, the system should display a "No results found" message instead of showing a blank page.
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by yashpreet2707**
closes #15

fixed the issue, now it shows "No Result Found"

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@yashpreet2707 can you please attach a screenshot/video of what you have done?

**Comment by yashpreet2707** [comment]
Screenshot 2023-05-20 at 1 55 04 PM

**Comment by yashpreet2707** [comment]
@AshutoshDash1999 Heyy there is an error in the above-mentioned solution which I've made a PR of.

Now I've figured out the solution. Can you please now delete that PR maybe and assign me under GSSOC'23 so that I can create a PR.

**Comment by yashpreet2707** [comment]
see this.

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/111020648/c996d227-3b29-461e-af9f-a04fd831ce1b

**Comment by AshutoshDash1999** [comment]
@yashpreet2707 you should always create a new issue and wait for being assigned. You didn't wait for assigning the issue and submitted a PR. This will not be entertained in future.

**Comment by yashpreet2707** [comment]
Actually ok very new to open source and i just learned about assigning of issues yesterday only. I'm really sorry for what I did.
Now can you please assign me that issue under GSSOC'23

**Pull request closed without merging**
