### PR TITLE
Contributors

### LINKED ISSUE #383: New Page for Contributors
### Is your feature request related to a problem? Please describe.

As this is an open-source project having a section dedicated to contributors is a common practice. I would like to add a page that contains the contributor's information in the card form.

### Describe the solution you'd like

We can do this in the following way:
I will add a link in the navbar to a page for contributors and on that page we will have a list of contributors who have contributed to this project. Later we can ask the contributors to add their names to the contribution page by themselves.

**Request** 

I am a gssoc23 contributor please assign me this issue under gssoc23 label.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## Description

Added contributors page
closes #383  **New Page for Contributors**

## Important Note
**You need to add GitHub public access token key in the contributor.js file to get the contributor's data.**

## Output

https://github.com/Bookingjini-Labs/bookingjini-icons/assets/86224794/e812fb68-7b39-4087-b5e6-3062e42fc6d1

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
The API is not working.
image


Check the network tab for the error message.

**Comment by AlfiyaSiddique** [comment]
You need to first generate the GitHub access token key and add it to the contribute.js file. 
We need to hide the key as well. You can inject variables during the build.

Here 👇🏻👇🏻

**Comment by AlfiyaSiddique** [comment]
Once you created the environment variable in the deployment, let me know the variable name and I'll add it to the code and then the code will work.

**Comment by AlfiyaSiddique** [comment]
Hello @AshutoshDash1999 , what about this PR progress, do I need to change something??

**Comment by AshutoshDash1999** [comment]
@AlfiyaSiddique can you DM me on Linkedin, your LinkedIn account link in your profile is broken. I will share the variable name over there.

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique can you DM me on Linkedin, your LinkedIn account link in your profile is broken. I will share the variable name over there.

Sure

Thanks for letting me know about my profile link. 👍🏻

**Comment by AlfiyaSiddique** [comment]
Hey @AshutoshDash1999 
Please review this PR. It worked!!

**Comment by AlfiyaSiddique** [comment]
Hello @AshutoshDash1999 
I have implemented the API, it's working, please review this PR

**Comment by AshutoshDash1999** [comment]
nice work 👍

**Pull request merged**
