### PR TITLE
made changes to header CSS

### PR DESCRIPTION
**Pull request by ks20soni**
Made a few changes to the header of the website in both light and dark modes.
1) Removed all extra paddings
2) Gave the existing transition to animated class to logo text to make it more appealing
3) Changed color of logo text from blue to black
4) On transition the color goes from blue to shade of pink (keeping it same as the color of link box so that it is contrast to the website)
5) Also gave an oblique style to the bold line after header

Previous Screenshots of the website:
Screenshot 2023-06-12 at 7 33 12 PM
Screenshot 2023-06-12 at 7 32 10 PM

After changes to website:
Screenshot 2023-06-12 at 7 32 37 PM
Screenshot 2023-06-12 at 7 32 48 PM

Post Transition look:
Screenshot 2023-06-12 at 7 42 26 PM
Screenshot 2023-06-12 at 7 42 37 PM

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@ks20soni this isn't looking good. just remove the extra padding. make sure the all the contents are in 1 line from top to bottom

**Comment by AshutoshDash1999** [comment]
@ks20soni this isn't looking good. just remove the extra padding. make sure the all the contents are in 1 line from top to bottom

**Comment by ks20soni** [comment]
> @ks20soni this isn't looking good. just remove the extra padding. make sure the all the contents are in 1 line from top to bottom

Sure. I'll do that.

**Comment by ks20soni** [comment]
I hope it looks fine now.

Screenshot 2023-06-18 at 11 13 57 PM
Screenshot 2023-06-18 at 11 14 08 PM

**Pull request merged**
