### PR TITLE
navbar and alignment of icons are responsive

### PR DESCRIPTION
**Pull request by picturepatch07**
The alignment of icons are responsive now

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@picturepatch07 please resolve merge conflict

**Comment by AshutoshDash1999** [comment]
@picturepatch07 any update on this?

**Comment by picturepatch07** [comment]
sorry for the delay, i was busy with my end semester exams, i am working on it

**Comment by picturepatch07** [comment]
Help me with resolving the conflicts

**Comment by AshutoshDash1999** [comment]
@picturepatch07 first take a pull from the dev branch and then add your edits

**Comment by picturepatch07** [comment]
@AshutoshDash1999 please check

**Comment by AshutoshDash1999** [comment]
its not responsive yet

1.
image

2.
image

**Comment by picturepatch07** [comment]
@AshutoshDash1999 from my end it is working fine, do let me know if i need to modify something

**Comment by AshutoshDash1999** [comment]
why the footer alignment is changed?
image

**Comment by AshutoshDash1999** [comment]
> why the footer alignment is changed?

**Pull request closed without merging**
