### PR TITLE
Logotext colour changed

### PR DESCRIPTION
**Pull request by I-shika**
#251 
For dark theme the colour of logotext is changed to white.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
This isn't looking good in light mode. Also, we don't need the hover effect for title.
image

**Comment by I-shika** [comment]
I have fixed it for light mode. Please look into it

**Comment by AshutoshDash1999** [comment]
please fix conflicts

**Comment by I-shika** [comment]
I have resolved them

**Comment by AshutoshDash1999** [comment]
Make this complete black:
image

Make this complete white:
image

**Comment by I-shika** [comment]
error resolved in new branch i.e, heading_colur_changed. PR has been raised

**Pull request closed without merging**
