### PR TITLE
Footer Section Updated [GSSOC'23]

### PR DESCRIPTION
**Pull request by fantasticbuddy**
I have updated the footer section as the issue was assigned to me. I have updated it for both light and dark themes and moreover i have added some hover effects to the icons and bookingjini-icons logo.

Light Theme -
image

Dark Theme -
image

Kindly review the request and merge the same.
@AshutoshDash1999 
Thankyou.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@riyaVerma1726 please
- add meaning full text in footer
- Pascal case the bookingjini icon text
- add social links the the respective icons. you can get all the links from bookingjini.com
- please improve the styling in light mode

**Comment by fantasticbuddy** [comment]
1. Do you have so catchy line to add in footer -
or is should add it myself. Something like - 
 "Illuminate Your Designs with bookingjini Icons"
or you want some paragraph to be added. If yes kindly provide that.

2. Since there is no twitter account so should I add whatsApp as one of the socials or just 3 are enough (linked in, facebook, instagram ).

3. In light mode you just want styling and colors to be changed or some addition or deletion in the content.

Please clear all these doubts. I will make changes and will send the PR again.
Thankyou @AshutoshDash1999

**Comment by fantasticbuddy** [comment]
Is this styling ok for light mode -
image

with icons and bookinjini icons possesing hover effects
@AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
> 1. Do you have so catchy line to add in footer -
>    or is should add it myself. Something like -
>    "Illuminate Your Designs with bookingjini Icons"
>    or you want some paragraph to be added. If yes kindly provide that.
> 2. Since there is no twitter account so should I add whatsApp as one of the socials or just 3 are enough (linked in, facebook, instagram ).
> 3. In light mode you just want styling and colors to be changed or some addition or deletion in the content.
> 
> Please clear all these doubts. I will make changes and will send the PR again. Thankyou @AshutoshDash1999

1. You can take suggestions from the project readme
2. yeah these 3 are enough
3. change styling...please take reference from other sites
4. please don't change the font
5. feel free to play with hover effect on social icons

**Comment by fantasticbuddy** [comment]
> > 1. Do you have so catchy line to add in footer -
> >    or is should add it myself. Something like -
> >    "Illuminate Your Designs with bookingjini Icons"
> >    or you want some paragraph to be added. If yes kindly provide that.
> > 2. Since there is no twitter account so should I add whatsApp as one of the socials or just 3 are enough (linked in, facebook, instagram ).
> > 3. In light mode you just want styling and colors to be changed or some addition or deletion in the content.
> > 
> > Please clear all these doubts. I will make changes and will send the PR again. Thankyou @AshutoshDash1999
> 
> 1. You can take suggestions from the project readme
> 2. yeah these 3 are enough
> 3. change styling...please take reference from other sites
> 4. please don't change the font
> 5. feel free to play with hover effect on social icons

I have made some changes to the footer. Kindly review the same. -
image

**Comment by AshutoshDash1999** [comment]
are you using any fonts for the ```bookingjini icons``` part?

**Comment by fantasticbuddy** [comment]
> are you using any fonts for the `bookingjini icons` part?

No, there's nothing
Do you want it same as this
image

Is this fine
image

**Comment by AshutoshDash1999** [comment]
can you reduce the top-bottom padding?

the `g` and `j` got cuts out from bottom while hovering.
image

**Comment by fantasticbuddy** [comment]
@AshutoshDash1999 
I removed the hovering effect from logo. Now effect is only on social icons.
Now there are no cuts.
Is that okay because footer is looking good with less animations.

Also is the color and styling fine. I made it blue to match with logo.

**Comment by AshutoshDash1999** [comment]
can you push the new code to the branch? so that i can see the deploy preview

**Comment by fantasticbuddy** [comment]
Okay just a seconds

**Comment by AshutoshDash1999** [comment]
> can you reduce the top-bottom padding?

Please work on this. The footer covers a large area which isn't required.

**Comment by fantasticbuddy** [comment]
Okay got this.
image

is this fine. or more reduction.

**Comment by AshutoshDash1999** [comment]
just add 10 more px then you are good to go

**Comment by fantasticbuddy** [comment]
> just add 10 more px then you are good to go

All done.
Should i push the code.

**Comment by AshutoshDash1999** [comment]
yes

@fantasticbuddy also alwyas name the branch based on what you are doing like `footer-enhancement`..keeping it as your name may create confusion.

**Comment by fantasticbuddy** [comment]
Done.
please merge it then i'II start working on the category issue
thankyou.

**Pull request merged**
