### PR TITLE
Added new day/night toggle button

### PR DESCRIPTION
**Pull request by SaiyamTuteja**
This commit introduces a new day/night toggle button to the Website. The toggle button allows users to switch between a day and night theme for a more personalized browsing experience. solved Issue -: **#403**
Screenshot 2023-07-20 031856
Screenshot 2023-07-20 031816

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
- why is there a colored box?
image

- the toggle is not changing to dark mode icon

**Comment by SaiyamTuteja** [comment]
ok i can change the code and then sync the repo as in my side its working

**Comment by AshutoshDash1999** [comment]
Please test the switch properly before pushing and review the deploy preview.

When the dark mode is switched to light mode and then switched back the switch changes but not the theme.

**Comment by SaiyamTuteja** [comment]
Ok but i think the java script is not working accordingly as i am not that much good in java script as i need help of anyone so you can merge my pull request then anyone can raise the isuues to solve this issue so please consider it

**Comment by AshutoshDash1999** [comment]
this is not good. you should complete your assigned task and not pile it for someone else

**Comment by AshutoshDash1999** [comment]
@khadar1020 since you worked on fixing this, can you work on this PR?

**Comment by khadar1020** [comment]
ok i will work on this issue @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
> ok i will work on this issue @AshutoshDash1999

Can you comment on the issue? #403

**Pull request closed without merging**
