### PR TITLE
made website completely responsive

### PR DESCRIPTION
**Pull request by akshaysoni10**
I have made website completely responsive. Issue #406 is solved.

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
why have you made seperate css file for responsiveness?

**Comment by ankit071105** [comment]
okay now i can get the chance to resolve the issue

**Comment by akshaysoni10** [comment]
@AshutoshDash1999 I didn't create any new file for responsiveness. responsiveness.css file is already there where all media queries were written. I just modify the code.

**Comment by AshutoshDash1999** [comment]
> okay now i can get the chance to resolve the issue

why do you think so? Akshay is already working on it.

**Comment by ankit071105** [comment]
okay i had not seen that @AshutoshDash1999

**Comment by AshutoshDash1999** [comment]
> @AshutoshDash1999 I didn't create any new file for responsiveness. responsiveness.css file is already there where all media queries were written. I just modify the code.


Ok  got it

**Pull request merged**
