### PR TITLE
search box performance improved  and bug solved

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
solved #293 

1.  **implement search box with debouncing** ( Debouncing is an optimization technique to limit the number of times a task is done.  )
2.  **search box bug solved** ( bug - 
I am not getting accurate results when typing anything in the search box. For example, if I type 'a,' the search results should display all icons starting with 'a,' but only 1 or 2 icons are appearing.
debouncing concept is not present in search box - In the context of a search box, debouncing is a technique used to control and optimize the execution of search queries or other related actions triggered by user input. When a user types into a search box, it often results in frequent events firing, such as keypress or input events. Each event may trigger an action, such as sending a request to a server to retrieve search results or updating the search suggestions. )

### CODE REVIEW

**Comment by mandliyarajendra11** [comment]
@ramanujamgond learn new string search  algo  ❤👍

**Comment by AshutoshDash1999** [comment]
> @ramanujamgond learn new string search algo ❤👍

I don't understand this. You are asking him to learn?

**Comment by mandliyarajendra11** [comment]
> > @ramanujamgond learn new string search algo ❤👍
> 
> I don't understand this. You are asking him to learn?

no bro i learn from this

**Comment by AshutoshDash1999** [comment]
cool

**Pull request merged**
