### PR TITLE
Top Image-logo and Logo-text issue #200

### PR DESCRIPTION
**Pull request by ATOMworkplace**
The issue with logo-text and logo-image alignment is fixed. 
The issue with icon and heading in light mode is fixed
Screenshot 2023-06-01 145634
Resolved issue #200
logo
logo-mobile-preview

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@ATOMworkplace please wait for the issue to be assigned. Then only submit a PR. Please make sure of this in future.

**Comment by ATOMworkplace** [comment]
> @ATOMworkplace please wait for the issue to be assigned. Then only submit a PR. Please make sure of this in future.

Sure, In the future, I'll ensure to wait for the issue to be assigned before submitting a pull request

**Comment by AshutoshDash1999** [comment]
The logo and other options should be align in 1 row except in mobile view

**Comment by ATOMworkplace** [comment]
> The logo and other options should be align in 1 row except in mobile view

I can fix the issue, can you assign me this issue under GSSOC'23

**Comment by ATOMworkplace** [comment]
> The logo and other options should be align in 1 row except in mobile view
Respective issues are resolved.
1-boj
2-boj
3-boj
4-boj

**Comment by AshutoshDash1999** [comment]
@ATOMworkplace why are you changing the font? its not required, on top of that you are not asked to do so

**Comment by ATOMworkplace** [comment]
> @ATOMworkplace why are you changing the font? its not required, on top of that you are not asked to do so

Ok, Actually I am new to open source so I don't know the extent to which I can change the code, but I have made the said changes and committed them in PR. **Thanks for cooperating**

1b
2b
3b
4b

**Pull request merged**
