### PR TITLE
Added about us and contact us page 

### LINKED ISSUE #17: request to make Contact us and about section

### PR DESCRIPTION
**Pull request by gaur15**

### CODE REVIEW

**Comment by AshutoshDash1999** [comment]
@gaur15 can you please share screenshot

**Comment by gaur15** [comment]
> @gaur15 can you please share screenshot

Screenshot 2023-06-02 202614
Screenshot 2023-06-02 202640
Screenshot 2023-06-02 202649
sir these are the screenshot of about us and contact page and blue color is because of the logo and hover effect on download are blue.
any changes sir

**Comment by AshutoshDash1999** [comment]
@gaur15 this is too much overdo for us. We don't need so much.

**Comment by gaur15** [comment]
> @gaur15 this is too much overdo for us. We don't need so much.

ok sir so what should I remove I can remove the bg color and make it look simple.
is about page ok? or should I remove the cards.
do suggest changes sir.

**Comment by AshutoshDash1999** [comment]
please add very minimalist footer. we dont need such cards or contact us section

**Pull request closed without merging**
